# configure updates globally, default is all
update: all # allowed [all, insecure, False]

# configure dependency pinning globally, default is True
pin: True # allowed [True, False]

# update schedule, default is not set
# the bot will visit the repo once and bundle all updates in a single PR for the given
# day/week/month
schedule: "every day" # allowed ["every day", "every week", "every two weeks", "every month"]

# configure requirement files search, default is True
# the bot will search for files ending with .txt/.pip with a requirements in their file paths
search: True # allowed [True, False]
